### ISSUE TITLE
Favorites don't are not kept after filtering

### ISSUE THREAD

**Issue by Cyber4sPopo** [RoyShnitzel/final-project-1#2]
Steps to reproduce:
1. Filter tickets with any word in search bar.
2. Add first ticket to Favorites
3. Remove filtering
4. Press "Display Favorites" button

**Expected Result:**
The ticket added to Favorites should be displayed

**Actual Result:**
An empty list is displayed

**Comment by RoyShnitzel** [comment]
fixed
